package com.omnitool.omni_tool.recipe;

import com.mojang.logging.LogUtils;
import com.omnitool.omni_tool.OmniToolMod;
import com.omnitool.omni_tool.registry.ModItems;
import net.minecraft.core.NonNullList;
import net.minecraft.core.RegistryAccess;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.PickaxeItem;
import net.minecraft.world.item.Tier;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.ShapedRecipe;
import net.minecraft.world.item.crafting.ShapelessRecipe;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * Turns every "pickaxe" crafting recipe into the matching Omni Tool recipe at runtime.
 *
 * <h2>Idea</h2>
 * Instead of shipping (or knowing) a list of supported materials, the cloner reads the recipes the
 * game actually loaded - vanilla, datapack and modded alike - and looks for recipes whose result is
 * a {@link PickaxeItem}:
 * <pre>
 *   for each recipe R with result PickaxeItem P:
 *       tier = P.getTier()
 *       omni = ModItems.omniToolForTier(tier)      // registered statically or by the dynamic layer
 *       if omni is absent        -> skip, log (graceful, never throws)
 *       if omni already craftable-> skip (keeps datagen recipes authoritative, stops duplicate recipes)
 *       otherwise                -> clone R with the result replaced by omni, same grid, same materials
 * </pre>
 *
 * <h2>Design notes</h2>
 * <ul>
 *   <li><b>Same materials and positions</b>: the cloned recipe copies {@code width}, {@code height}
 *       and the full ingredient grid of the source recipe verbatim. Only the result stack changes,
 *       so a modded "tin pickaxe" recipe automatically yields the matching Omni Tool in exactly the
 *       shape the mod author designed.</li>
 *   <li><b>Idempotent</b>: the "already craftable" guard means repeated invocations (the sync event
 *       fires once per joining player) never stack up duplicates.</li>
 *   <li><b>No crash policy</b>: every failure mode - unknown tier, unsupported recipe class,
 *       unexpected exception - results in a skipped recipe plus a log line.</li>
 * </ul>
 *
 * <h2>Known limitation</h2>
 * Only {@link ShapedRecipe} and {@link ShapelessRecipe} can be cloned. A modded pickaxe produced by
 * a custom {@code RecipeSerializer} (for example a smithing-table or machine recipe) is counted and
 * logged as "unsupported" and is skipped. The vanilla six tiers are unaffected because they are
 * generated by data generation instead of being cloned.
 */
public final class OmniToolRecipeCloner {

    private static final Logger LOGGER = LogUtils.getLogger();

    /** Everything a dynamic tool needs to look like its source recipe. */
    private static final String ID_FOLDER = "dynamic";

    private OmniToolRecipeCloner() {
    }

    /**
     * Clones every clonable pickaxe recipe found in {@code existingRecipes}.
     *
     * @param existingRecipes the recipes currently known to the recipe manager
     * @param registries      registry access used to resolve recipe results
     * @return the additional recipes to add; empty when there is nothing to do
     */
    public static List<Recipe<?>> clonePickaxeRecipes(Collection<Recipe<?>> existingRecipes,
                                                      RegistryAccess registries) {
        Set<Item> alreadyCraftable = new HashSet<>();
        for (Recipe<?> recipe : existingRecipes) {
            ItemStack result = resultOf(recipe, registries);
            if (!result.isEmpty()) {
                alreadyCraftable.add(result.getItem());
            }
        }

        List<Recipe<?>> clones = new ArrayList<>();
        int skippedNoTool = 0;
        int skippedAlreadyCraftable = 0;
        int skippedUnsupported = 0;

        for (Recipe<?> recipe : existingRecipes) {
            ItemStack result = resultOf(recipe, registries);
            if (result.isEmpty() || !(result.getItem() instanceof PickaxeItem pickaxeItem)) {
                continue;
            }

            Tier tier = pickaxeItem.getTier();
            Optional<Item> omniTool = ModItems.omniToolForTier(tier);
            if (omniTool.isEmpty()) {
                // Legitimate outcome: a material whose tier has no Omni Tool (for example a pickaxe
                // created by an item that is not backed by a registered Tier).
                skippedNoTool++;
                LOGGER.debug("[OmniTool] No Omni Tool registered for tier of {} (level {}, speed {}); "
                                + "skipping recipe {}",
                        result.getItem(), tier.getLevel(), tier.getSpeed(), recipe.getId());
                continue;
            }

            Item target = omniTool.get();
            if (alreadyCraftable.contains(target)) {
                // Either a data generated recipe for a vanilla tier, or a clone produced earlier.
                skippedAlreadyCraftable++;
                continue;
            }

            Recipe<?> clone = cloneOne(recipe, target, result.getCount(), registries);
            if (clone == null) {
                skippedUnsupported++;
                continue;
            }
            clones.add(clone);
            alreadyCraftable.add(target);
        }

        if (!clones.isEmpty() || skippedUnsupported > 0 || skippedNoTool > 0) {
            LOGGER.info("[OmniTool] Dynamic recipe pass: {} cloned, {} already craftable, "
                            + "{} skipped (no matching tier), {} skipped (unsupported recipe type)",
                    clones.size(), skippedAlreadyCraftable, skippedNoTool, skippedUnsupported);
        }
        return clones;
    }

    /**
     * Builds a single clone.
     *
     * @return the cloned recipe, or {@code null} when the recipe class cannot be cloned
     */
    private static Recipe<?> cloneOne(Recipe<?> recipe, Item target, int count,
                                      RegistryAccess registries) {
        ResourceLocation sourceId = recipe.getId();
        ResourceLocation cloneId = new ResourceLocation(OmniToolMod.MOD_ID,
                ID_FOLDER + "/" + sourceId.getNamespace() + "/" + sourceId.getPath());
        ItemStack result = new ItemStack(target, Math.max(1, count));

        if (recipe instanceof ShapedRecipe shaped) {
            NonNullList<Ingredient> ingredients = NonNullList.create();
            ingredients.addAll(shaped.getIngredients());
            return new ShapedRecipe(cloneId, shaped.getGroup(), shaped.category(),
                    shaped.getWidth(), shaped.getHeight(), ingredients, result,
                    shaped.showNotification());
        }

        if (recipe instanceof ShapelessRecipe shapeless) {
            NonNullList<Ingredient> ingredients = NonNullList.create();
            ingredients.addAll(shapeless.getIngredients());
            return new ShapelessRecipe(cloneId, shapeless.getGroup(), shapeless.category(),
                    result, ingredients);
        }

        LOGGER.debug("[OmniTool] Recipe {} uses {} which cannot be cloned; skipped",
                sourceId, recipe.getClass().getSimpleName());
        return null;
    }

    private static ItemStack resultOf(Recipe<?> recipe, RegistryAccess registries) {
        try {
            ItemStack result = recipe.getResultItem(registries);
            return result == null ? ItemStack.EMPTY : result;
        } catch (Throwable throwable) {
            // A modded recipe implementation may need more data than we can provide; it must not
            // break the whole pass.
            LOGGER.debug("[OmniTool] Could not resolve the result of recipe {}", recipe.getId(), throwable);
            return ItemStack.EMPTY;
        }
    }
}
